import React from 'react';
import $ from 'jquery';
import {connect} from 'react-redux';
import rootReducer from "../reducers/Spotify";
import generalActions from "../actions";
import ArtistList from "./ArtistList";
import NextPrevButton from "./NextPrevButton";
import Error from "./Error";
import marked from "marked";
import AlbumList from "./AlbumList";
import {sendAjaxRequest} from "../modules/sendAjaxRequest";

//todos: eliminate flashing of objects between different categories.
//artists profile with biography
//add new release button to search bar
//add genre to album
//do more character encoding for search query string parameters
//move next and previous navigation into a component for reuse

class Search extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			errorText:null
		}
		//bind various function with context for onClicks
		this.startSearch = this.startSearch.bind(this);
		this.ajaxError = this.ajaxError.bind(this);
		this.setListingData = this.setListingData.bind(this)
		this.showSearch = this.showSearch.bind(this)
		this.showNewRelease = this.showNewRelease.bind(this)
		this.setNewReleasesData = this.setNewReleasesData.bind(this)
		this.getAlbumsDetails = this.getAlbumsDetails.bind(this)
		this.addAlbumDetailsToResults = this.addAlbumDetailsToResults.bind(this)
	}
	componentDidMount() {
		//show new releases on default to make search page useful
		this.showNewRelease()
	}
	componentDidCatch(error, info) {
	}
	setListingData(output){
		//receive ajax output
		this.props.setAjaxError(null);
		//pass results to redux store
		this.props.setResults(output);
	}
	setNewReleasesData(output){
		//receive ajax output
		this.props.setAjaxError(null);
		//pass results to redux store
		this.props.setResults(output);
		//gets further details of album not available in simple album format
		this.getAlbumsDetails();
	}
	addAlbumDetailsToResults(output){
		//combined deeper album details with album items in redux store 
		this.props.setAjaxError(null);
		this.props.addAlbumDetails(output);
	}
	newIcon(){
		//new releases icon
		//<!-- Icon Generated by IcoMoon.io -->
		let icon = marked('<svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M10.031 32c-2.133-4.438-0.997-6.981 0.642-9.376 1.795-2.624 2.258-5.221 2.258-5.221s1.411 1.834 0.847 4.703c2.493-2.775 2.963-7.196 2.587-8.889 5.635 3.938 8.043 12.464 4.798 18.783 17.262-9.767 4.294-24.38 2.036-26.027 0.753 1.646 0.895 4.433-0.625 5.785-2.573-9.759-8.937-11.759-8.937-11.759 0.753 5.033-2.728 10.536-6.084 14.648-0.118-2.007-0.243-3.392-1.298-5.312-0.237 3.646-3.023 6.617-3.777 10.27-1.022 4.946 0.765 8.568 7.555 12.394z"></path></svg>', {sanitize: false});
		return { __html: icon };
	}
	searchIcon(){
		//<!-- Icon Generated by IcoMoon.io -->
		let icon = marked('<svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M31.008 27.231l-7.58-6.447c-0.784-0.705-1.622-1.029-2.299-0.998 1.789-2.096 2.87-4.815 2.87-7.787 0-6.627-5.373-12-12-12s-12 5.373-12 12 5.373 12 12 12c2.972 0 5.691-1.081 7.787-2.87-0.031 0.677 0.293 1.515 0.998 2.299l6.447 7.58c1.104 1.226 2.907 1.33 4.007 0.23s0.997-2.903-0.23-4.007zM12 20c-4.418 0-8-3.582-8-8s3.582-8 8-8 8 3.582 8 8-3.582 8-8 8z"></path></svg>', {sanitize: false});
    	return { __html: icon };
	}
	getAlbumsDetails(){
		//gets album ids from simple albums items and do a batch ajax request for details
		var album_ids = "";

		//create url parameter of album ids
		this.props.info.results.items.map((album,index)=>{
			album_ids += album.id + ((index<(this.props.info.results.items.length-1))?",":"");
		});
		//build url
		let url =  `${this.props.info.spotify_base}/albums?ids=${album_ids}`;
		sendAjaxRequest(url,this.props.info.token,this.addAlbumDetailsToResults,this.ajaxError);
	}
	ajaxError(jqXHR, textStatus){
		console.log(jqXHR)
		console.log(textStatus)
		//if ajax error set message object which switches user back to login
		this.props.setAjaxError(jqXHR.responseJSON);
	}
	startSearch(e){
		e.preventDefault();
		//var search_string = String($("input[name=query]").val()).replace(/\s/g,"%20");
		var search_string = encodeURIComponent($("input[name=query]").val());

		//search string needs to be a word character
		if(search_string.match(/\w/)){
			this.props.setCategory("artists"); //set category for artists layout
			this.props.setArtist(null); //resets artists selected
			this.setState({errorText:null}); //sets ajax error to null

			//construct search url
			var search_url = this.props.info.search.url + search_string + this.props.info.search.param + this.props.info.search.subject;

			//ajax function put in module for reuse
			sendAjaxRequest(search_url,this.props.info.token,this.setListingData,this.ajaxError);	
		}
		else{

			//sets small error message above serach bar
			this.setState({errorText:"Please Enter a Search String"});
		}
		
	}
	showNewRelease(){
		this.props.setCategory("newreleases");
		this.showSearch();
		var new_releases_url = this.props.info.spotify_base + this.props.info.new_releases_path;
		sendAjaxRequest(new_releases_url,this.props.info.token,this.setNewReleasesData,this.ajaxError);
	}
	showSearch(){
		//resets artist name to show search bar
		this.props.setArtist(null);
	}
	showArtistName(){
		//shows artist nav with sub nav in header
		return (
			<div className="artist-title-area">
			<h1>{this.props.info.selected_artist.name}</h1>
				<div className="artist-title-nav">
				<button className="show-new" onClick={this.showNewRelease}><span dangerouslySetInnerHTML={this.newIcon()}></span></button>
				<button className="show-search" onClick={this.showSearch}><span dangerouslySetInnerHTML={this.searchIcon()}></span></button>
				</div>
	    	</div>
		)
	}
	searchArea(){		
		return (
			<div className="search-input-area">
	    	<h1>Search Artists</h1>
	    	<form className="search_form">
	    		{ this.state.errorText &&
	    			(<Error errorText={this.state.errorText}/>)
	    		}
	    		<input type="text" name="query" placeholder="Enter Your Query" />
	    		<button type="submit" onClick={this.startSearch}><span dangerouslySetInnerHTML={this.searchIcon()}></span></button>
	    	</form>
	    	</div>
		)
	}
	render() {
		var listing = null;
		//change layout depeneding on category
		switch(this.props.info.category){
			case 'artists':
				listing = <ArtistList/>
				break;
			case 'albums':
				listing = <AlbumList/>
				break;
			case 'newreleases':
				listing = <AlbumList/>
				break;
		}
		
	    return (
	    	<div>
	    	{/* shows search bar or artist name */}
	    	{ this.props.info.selected_artist == null && this.searchArea() }
	    	{ this.props.info.selected_artist != null && this.showArtistName() }

	    	<div className="next-prev-navigation">
		    	{this.props.info.prev_url != null &&
		    		<NextPrevButton url={this.props.info.prev_url} text="Previous" />
		    	}
		    	{this.props.info.next_url != null &&
		    		<NextPrevButton url={this.props.info.next_url} text="Next" />
		    	}
	    	</div>
	    	
	    	{/* displays album or artists listings */}
	    	{ this.props.info.results != null && 
				listing
	    	}

	    	<div className="next-prev-navigation">
		    	{this.props.info.prev_url != null &&
		    		<NextPrevButton url={this.props.info.prev_url} text="Previous" />
		    	}
		    	{this.props.info.next_url != null &&
		    		<NextPrevButton url={this.props.info.next_url} text="Next" />
		    	}
	    	</div>

	    	</div>

	    )
  }
}

//redux store connection to component propety
const mapStateToProps = function(state){
	return {"info":state};		
}

//redux reducers connections - passes objects for filtering
 const mapDispatchToProps = function(dispatch) {
    return({
        setResults: (results) => {
        	dispatch({type:"SET_RESULTS","results":results})
        },
        setArtist: (artist_obj) => {
        	dispatch({type:"SET_ARTIST","artist":artist_obj})
        },
        addAlbumDetails: (results) => {
        	dispatch({type:"ADD_ALBUM_DETAILS","results":results})
        },
        setCategory: (category) => {
        	dispatch({type:"SET_SEARCH_CATEGORY","category":category})
        },
        setAjaxError: (error) => {
        	dispatch({type:"SET_AJAX_ERROR","error":error})
        }
    })
}
//connext component to redux
export default connect(mapStateToProps,mapDispatchToProps)(Search)

